/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { AdditiveBlending } from 'three'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/moon.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh 
        geometry={nodes.Cube008.geometry} 
        material={materials['Default OBJ.005']} 
        scale={[0.003, 0.003, 0.003]} 
        material-transparent={true} 
        material-opacity={0.98} 
        material-blending={AdditiveBlending}
        />
    </group>
  )
}

useGLTF.preload('/moon.glb')
